### PR TITLE
Restrict range

### PR DESCRIPTION
**Pull request by nicebread**
Dear contributors, if you find some spare minutes, could you take a look at this new release?

- new feature: restrict range on which data is estimated. (e.g.: estimate exponential growth in Italy before intervention (days 1-16 if you consider "since 100 cases") and see how the curve flattens
- new section: "Putting these numbers in context" with some caveats how (not) to interpret these numbers. Suggestions/references welcome!

A live version is here:
http://shinyapps.org/apps/corona_dev/

### CODE REVIEW

**Comment by nicebread** [comment]
E.g.:
grafik

**Comment by astefan1** [comment]
I'll adjust the download button again ;-)

**Comment by astefan1** [comment]
I couldn't find any information about Italy conducting post-mortem tests, but the US seems to do them (there is a CDC guidance for it): https://www.cdc.gov/coronavirus/2019-ncov/hcp/guidance-postmortem-specimens.html

**Comment by astefan1** [comment]
> I'll adjust the download button again ;-)

Created a pull request for this. It would be good to merge that first before publishing this branch.

**Pull request merged**
