### PR TITLE
Add CSSE_2020-03-15.csv and fix update mechanism

### PR DESCRIPTION
**Pull request by zuphilip**
(Please also restart the shiny app or whatever is needed to use the updated numbers.)

### CODE REVIEW

**Comment by nicebread** [comment]
Thanks! I have to update the automatic download function, then these manual adds should not be necessary any more.

**Comment by zuphilip** [comment]
There is an update of this mechanism in this PR. - However, I think that this will currently only work when you start the app, right?

**Comment by nicebread** [comment]
Right. I'm not sure what the best way is to balance server load and timeliness ... Maybe a cheap check check whether a remote file has changed (that is always performed), and then download it?

**Comment by zuphilip** [comment]
There is an example with buses which updates very minute the data for their position https://github.com/binder-examples/r which may be helpful. But I am not skilled enough in R to understand resp. do anything like this. Maybe you can do that? Otherwise we could open a new issue and flag it with "help wanted".

**Pull request merged**
